version: '3.8'
services:
  mysql:
    container_name: symfony_test_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3306:3306'
    volumes:
      - ./docker/data/mysql:/var/lib/mysql

  redis:
    container_name: symfony_test_redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
      - ./docker/development/redis/redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint:
      - redis-server
      - "--appendonly yes"

  php:
    container_name: symfony_test_php
    build:
      context: ./docker/development/php
    ports:
      - '9000:80'
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis

  nginx:
    container_name: symfony_test_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  redis_commander:
    container_name: symfony_test_redis_commander
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
